### ISSUE TITLE
Enhanced performance: Link instead of A href

### ISSUE THREAD

**Issue by NoobFullStack** [akoskm/nextjs-13-appdir-job-board#1]
I enjoy a lot reading your blogs, and have little to none to add. 

You might be aware of this already, but to enhance the performance even more, you can include the NextJS Link component: 

app\page.tsx -> line 22
```<a href={`jobs/${job.slug}`}>View Job</a>```
to:
```<Link href={`jobs/${job.slug}`}>View Job</Link>```

and

jobs\[slug]\page.tsx -> line 32
```<a href={'/'}>Go Back</a>```
to:
```<Link href={'/'}>Go Back</Link>```

The loading of those targets will be done on page load, providing even more performance for the website!
Don't forget to include ```import Link from 'next/link'```

Happy coding :)

**Comment by akoskm** [comment]
Thank you @1NoobDev, for the kind words! This would be a great improvement indeed.

I'm already using the Link component in React Router, but I wasn't aware that you have them in NextJS!

If you want, you can create a PR, and I'll merge it.

**Comment by NoobFullStack** [comment]
Great, my first PR 😊 I'll create it when I get back home
